name: Main branch

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Weekly rebuild of Docker image
    - cron: '38 11 * * 1'

concurrency:
  group: docker-image
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.9'
        distribution: 'graalvm'
    - name: Set up Node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '16.x'
    - name: Install Node dependencies
      run: npm ci
      working-directory: ./ep-tool-server
    - name: Push Docker Image
      uses: gradle/gradle-build-action@v3.1.0
      with:
        arguments: build dockerPush
    - name: Publish package
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}