name: Pull requests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'graalvm'
    - name: Set up Node
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '16.x'
    - name: Install Node dependencies
      run: npm ci
      working-directory: ./ep-tool-server
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3.1.0
      with:
        arguments: build
